import { useState } from 'react'
import './App.css'

function App() {
  const [activeTab, setActiveTab] = useState('home')

  const tabs = [
    { id: 'home', label: 'Home' },
    { id: 'detector', label: 'Detector' },
    { id: 'ai-image', label: 'AI Image Detector' },
    { id: 'fake-news', label: 'Fake News' },
    { id: 'about', label: 'About Us' }
  ]

  const renderTabContent = () => {
    switch (activeTab) {
      case 'home':
        return (
          <div className="hero-section">
            <div className="hero-content">
              <h1 className="hero-title">
                Welcome to the AI & Fake News Detection App
              </h1>
              <p className="hero-description">
                Use the tabs above to switch between the AI vs Human Text
                Detector, Fake News Detector, and learn more About Us.
              </p>
              
              {/* Feature Cards */}
              <div className="feature-cards">
                <div className="feature-card" onClick={() => setActiveTab('detector')}>
                  <div className="feature-icon">🤖</div>
                  <h3>AI Text Detection</h3>
                  <p>Detect AI-generated content with advanced algorithms</p>
                </div>
                
                <div className="feature-card" onClick={() => setActiveTab('ai-image')}>
                  <div className="feature-icon">🖼️</div>
                  <h3>Image Analysis</h3>
                  <p>Identify manipulated or AI-generated images</p>
                </div>
                
                <div className="feature-card" onClick={() => setActiveTab('fake-news')}>
                  <div className="feature-icon">📰</div>
                  <h3>Fake News Detection</h3>
                  <p>Verify news articles and detect misinformation</p>
                </div>
              </div>
              
              {/* CTA Buttons */}
              <div className="cta-buttons">
                <button 
                  className="cta-button primary"
                  onClick={() => setActiveTab('detector')}
                >
                  Start Detection
                </button>
                <button 
                  className="cta-button secondary"
                  onClick={() => setActiveTab('about')}
                >
                  Learn More
                </button>
              </div>
            </div>
          </div>
        )
      
      case 'detector':
        return (
          <div className="tab-content">
            <div className="content-header">
              <h2>AI Text Detector</h2>
              <p>Paste your text below to check if it was generated by AI</p>
            </div>
            <div className="detector-interface">
              <textarea 
                className="text-input"
                placeholder="Paste your text here to analyze..."
                rows={10}
              />
              <div className="detector-controls">
                <button className="analyze-button">Analyze Text</button>
                <button className="clear-button">Clear</button>
              </div>
              <div className="result-placeholder">
                <p>Results will appear here after analysis</p>
              </div>
            </div>
          </div>
        )
      
      case 'ai-image':
        return (
          <div className="tab-content">
            <div className="content-header">
              <h2>AI Image Detector</h2>
              <p>Upload an image to check if it was generated by AI</p>
            </div>
            <div className="image-detector-interface">
              <div className="upload-area">
                <div className="upload-icon">📁</div>
                <p>Drag and drop an image here or click to browse</p>
                <button className="upload-button">Choose Image</button>
              </div>
              <div className="result-placeholder">
                <p>Upload an image to see analysis results</p>
              </div>
            </div>
          </div>
        )
      
      case 'fake-news':
        return (
          <div className="tab-content">
            <div className="content-header">
              <h2>Fake News Detector</h2>
              <p>Enter a news article or URL to verify its authenticity</p>
            </div>
            <div className="news-detector-interface">
              <div className="input-options">
                <button className="input-type-button active">Text Input</button>
                <button className="input-type-button">URL Input</button>
              </div>
              <textarea 
                className="text-input"
                placeholder="Paste the news article text here..."
                rows={8}
              />
              <div className="detector-controls">
                <button className="analyze-button">Verify News</button>
                <button className="clear-button">Clear</button>
              </div>
              <div className="result-placeholder">
                <p>Verification results will appear here</p>
              </div>
            </div>
          </div>
        )
      
      case 'about':
        return (
          <div className="tab-content">
            <div className="about-content">
              <h2>About NoCapBot</h2>
              <div className="about-sections">
                <div className="about-section">
                  <h3>🎯 Our Mission</h3>
                  <p>
                    NoCapBot is dedicated to combating misinformation and AI-generated content 
                    by providing powerful detection tools that help users identify fake news, 
                    AI-generated text, and manipulated images.
                  </p>
                </div>
                
                <div className="about-section">
                  <h3>🔬 How It Works</h3>
                  <p>
                    Our advanced AI algorithms analyze patterns, linguistic markers, and 
                    visual artifacts to determine the authenticity of content. We use 
                    state-of-the-art machine learning models trained on vast datasets.
                  </p>
                </div>
                
                <div className="about-section">
                  <h3>🛡️ Why It Matters</h3>
                  <p>
                    In an era of increasing misinformation and AI-generated content, 
                    having reliable detection tools is crucial for maintaining trust 
                    and authenticity in digital communications.
                  </p>
                </div>
              </div>
            </div>
          </div>
        )
      
      default:
        return null
    }
  }

  return (
    <div className="app">
      {/* Navigation */}
      <nav className="navbar">
        <div className="nav-container">
          <div className="nav-tabs">
            {tabs.map((tab) => (
              <button
                key={tab.id}
                className={`nav-tab ${activeTab === tab.id ? 'active' : ''}`}
                onClick={() => setActiveTab(tab.id)}
              >
                {tab.label}
              </button>
            ))}
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <main className="main-content">
        {renderTabContent()}
      </main>
    </div>
  )
}

export default App


aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa