import React from 'react';

const AIImageDetector: React.FC = () => {
  return (
    <div className="page-container">
      <div className="tab-content">
        <div className="content-header">
          <h2>AI Image Detector</h2>
          <p>Upload an image to check if it was generated by AI</p>
        </div>
        <div className="image-detector-interface">
          <div className="upload-area">
            <div className="upload-icon">📁</div>
            <p>Drag and drop an image here or click to browse</p>
            <button className="upload-button">Choose Image</button>
          </div>
          <div className="result-placeholder">
            <p>Upload an image to see analysis results</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AIImageDetector;
