import React from 'react';

const Detector: React.FC = () => {
  return (
    <div className="page-container">
      <div className="tab-content">
        <div className="content-header">
          <h2>AI Text Detector</h2>
          <p>Paste your text below to check if it was generated by AI</p>
        </div>
        <div className="detector-interface">
          <textarea 
            className="text-input"
            placeholder="Paste your text here to analyze..."
            rows={10}
          />
          <div className="detector-controls">
            <button className="analyze-button">Analyze Text</button>
            <button className="clear-button">Clear</button>
          </div>
          <div className="result-placeholder">
            <p>Results will appear here after analysis</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Detector;

